language: c

addons:
  apt:
    packages:
    - subversion 
    - build-essential 
    - libncurses5-dev 
    - zlib1g-dev 
    - gawk 
    - git 
    - ccache 
    - gettext 
    - libssl-dev 
    - xsltproc

cache:
    directories:
    - $HOME/.cache

before_install:
    - rm -rf $HOME/openwrt
    - bash get-toolchain.sh

install: 
    - bash install-package.sh

script:
    - bash build-package.sh 
